name: CommandRandomKeys
version: '${project.version}'
main: es.ponnythelight.commandrandomkeys.CommandRandomKeys
api-version: 1.18
authors: [ PonnyTheLight ]
description: Create random keys to execute commands.
website: https://github.com/PonnyTheLight
commands:
  randomkeys:
    description: Plugin main command.
    aliases: [rk,crk, cmdrandomkeys, commandrandomkeys, crkeys, crk]
  createkey:
    description: Create new random key.
    aliases: [ckey, crkcreate]
  key:
    description: Redeem key generated.
    aliases: [claimkey, usekey, keyuse, keyclaim, crkclaim, crkuse, crkey]
  delkey:
    description: Delete a key.
    aliases: [ deletekey, removekey, dkey, rkey, crkremove, crkdelete, crkr, crkd ]